#!/bin/sh

if [ "$(whoami)" != "root" ]; then
  echo "The script require root privilege to execute properly.  Current identity: $(whoami)"
  exit 1
fi

# Install Compound library.
echo "Installing libcompound:"
cp -v "libcompound.so" "/usr/lib"

