#!/bin/sh

if [ "$(whoami)" != "root" ]; then
  echo "The script require running identity as root.  Current identity: $(whoami)"
  exit 1
fi

# Install Compound library.
echo "Installing libcompound:"
cp -v "out/libcompound.so" "/usr/lib"

