#!/bin/sh

DST=/usr/include/Compound

# Create directory.
[ ! -d "$DST" ] && mkdir -pv "$DST"

# Install headers.
cp -vr inc/* "$DST" || ( printf "\nPre-installation failed.\n" >&2 && exit 1 )

printf "\nProcedure succeeded.\n"
