#ifndef COMPOUND_ACCESS_PERMISSION_QUALIFIER_H
# define COMPOUND_ACCESS_PERMISSION_QUALIFIER_H

typedef enum {
  PRIVATE = 0,
  PROTECTED = 1,
  PACKAGE = 2,
  PUBLIC = 3,
} AccessPermissionQualifier;

#endif  /* COMPOUND_ACCESS_PERMISSION_QUALIFIER_H */
